spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      auto-offset-reset: earliest
      enable-auto-commit: false
  application:
    name: NotificationSenderGitService
  mail:
    host: smtp.mail.ru  # SMTP сервер
    port: 465              # Порт SMTP сервера
    username: asimbek06@mail.ru
    password: DnL00SdEdm3kZYKLptzr            # Пароль для SMTP
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9283/eureka/
