spring:
  cloud:
    gateway:
      routes:
        - id: ReleaseGitService
          uri: lb://RELEASEGITSERVICE
          predicates:
            - Path=/releases/**
#          filters:
#            - AuthenticationFilter

        - id: NotificationSenderGitService
          uri: lb://NOTIFICATIONSENDERGITSERVICE
          predicates:
            - Path=/notification/**

        - id: ApplicationGitService
          uri: lb://APPLICATIONGITSERVICE
          predicates:
            - Path=/app/**
          filters:
            - AuthenticationFilter

        - id: UserGitService
          uri: lb://USERGITSERVICE
          predicates:
            - Path=/users/**
  #          filters:
  #            - AuthenticationFilter
  application:
    name: GatewayGitService
server:
  port: 5743

eureka:
  client:
    service-url:
      defaultZone : http://localhost:9283/eureka/