spring:
  jpa:
    open-in-view:
      true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://Localhost:3306/UserGitPulseData
    username: root
    password: Zxcvbnm2006?
  application:
    name: UserGitService
server:
  port: 9235
eureka:
  client:
    service-url:
      defaultZone : http://localhost:9283/eureka/
